title: "GMA-IRE Newsletter"
name: "GMA-IRE Newsletter"
description: "Aggiornamenti mensili su opportunità, eventi, e ricerca"
url: "https://edoardoidaPhd.github.io/"

# impostazioni newsletter
paginate: 5
paginate_path: "/page:num/"

# autore
author:
  name   : "Edoardo Ida'"
  bio    : "Ricercatore, newsletter editor"
  location : "Italia"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/username"
theme: jekyll-theme-primer

# plugins (obbligatori su GH Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
